### ISSUE TITLE
Inconsistent use of laguange on motor.py

### ISSUE THREAD

**Issue by Luis-omega** [6abef/OXO#1]
The use of the world `cercle` in `motor.py` suggest the use of Frech, however the rest of the module uses english, maybe we should stick to a language? 

I didn't look for other words, but if there exists, replacing them should be part of this issue

**Comment by 6abef** [comment]
Okay, I’m going to use English but I got a little lost when translating from Spanish because I was mixing languages. I’ll figure it out in the next update.

**Comment by Luis-omega** [comment]
Don't worry, if you enable the protection of main branch on GitHub and we use reviews, the chances of a miss would lower . (See the related issue) .

**Comment by Luis-omega** [comment]
Where is the pr for this?
