### ISSUE TITLE
Remove pycache

### ISSUE THREAD

**Issue by Luis-omega** [6abef/OXO#3]
at top level of the project the folder `__pycache__` should be removed from the repo.

**Comment by Luis-omega** [comment]
Where is the pr for this? Reopen.

**Comment by 6abef** [comment]
Sorry, what does pr mean?

**Comment by Luis-omega** [comment]
Pull request, you need to open a branch, put your changes there, commit, then use `git push origin Branch_name` , then go to the repo on GitHub under the "pull request" tab
